name: Publish Docker Image
on:
  - push
jobs:
  e2e:
    uses: ./.github/workflows/e2e.yml
  push-to-ghcr:
    name: Push Docker image to GitHub Packages
    needs:
      - e2e
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get short SHA
        id: short
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: prod
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ot-sim:${{ steps.short.outputs.sha }}
            ghcr.io/${{ github.repository }}/ot-sim:${{ steps.short.outputs.branch }}
