name: Publish Docker Image
on:
  - push
jobs:
  e2e:
    uses: ./.github/workflows/e2e.yml
  push-to-ghcr:
    name: Push Docker image to GitHub Packages
    needs:
      - e2e
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/ot-sim
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
